### ISSUE TITLE
comm_can_set_pos_spd is wrong in example servo code

### ISSUE THREAD

**Issue by theserialhobbyist** [lezgin-alimoglu/CubeMars-AK60-6#3]
Thank you for sharing your code, it has been very helpful! But I wanted to point that the position-speed function code is wrong. It should look like this:

```
void comm_can_set_pos_spd(uint8_t controller_id, float pos, int16_t spd, int16_t RPA) {
  int32_t send_index = 0;
  int16_t send_index1 = 4;
  uint8_t buffer[8];
  buffer_append_int32(buffer, (int32_t)(pos * 10000.0), &send_index);
  buffer_append_int16(buffer, spd/10.0, &send_index1);
  buffer_append_int16(buffer, RPA/10.0, &send_index1);
  comm_can_transmit_eid(canId(controller_id, AKMode::AK_POSITION_VELOCITY), buffer, send_index1);
}
```

**Comment by lezgin-alimoglu** [comment]
Thank you for interest :) 
You are right, the buffer should be 8 byte, I missed this point.
I update my code now.

**Comment by lezgin-alimoglu** [comment]
Also index1 should start from 4, I missed also this part, thank you

**Comment by theserialhobbyist** [comment]
Yep! Also:

They divide both spd and RPA by 10.0, and use send_index1 as the final parameter in comm_can_transmit_eid().

(for the record, I'm just pulling that from the CubeMars manual)

**Comment by lezgin-alimoglu** [comment]
I can't be sure because I did it one years ago, however I will write a comment to check it.

**Comment by lezgin-alimoglu** [comment]
Ok I added the comment that "check it from manuel before use it". Thanks again

**Comment by theserialhobbyist** [comment]
Totally understandable! The code I posted is currently working for me, but I don't fully understand the structure of the CAN messages the driver is expecting, so I don't want to overpromise, haha.

**Comment by lezgin-alimoglu** [comment]
Yeah, I also use the manual and copy for most of the code. Probably you are right to change values if it works :) 
If you see any problem in my code, just share with me to change.
good luck you in your work :)
