### ISSUE TITLE
Set Origin Not Implemented?

### ISSUE THREAD

**Issue by theserialhobbyist** [lezgin-alimoglu/CubeMars-AK60-6#4]
Hi again! I just noticed the following in your code for the function to set the origin:

void comm_can_set_origin(uint8_t controller_id, uint8_t set_origin_mode) {
  int32_t send_index = 0;
  uint8_t buffer[4];
  comm_can_transmit_eid(canId(controller_id, AKMode::AK_ORIGIN), buffer, send_index);
}

That can't be right, can it? The passed "set_origin_mode" value isn't actually being used.

Do you know the solution? I'm struggling to understand the code (my C++ is weak) and I've tried a few things, but can't get it working and so I'm unable to set the motor origin.

**Comment by theserialhobbyist** [comment]
Ah dang, I spoke too soon! This seems to work...just added the buffer_append_int32() line:

void comm_can_set_origin(uint8_t controller_id, uint8_t set_origin_mode) {
  int32_t send_index = 0;
  uint8_t buffer[4];
  buffer_append_int32(buffer, (int32_t)set_origin_mode, &send_index);
  comm_can_transmit_eid(canId(controller_id, AKMode::AK_ORIGIN), buffer, send_index);
}

**Comment by lezgin-alimoglu** [comment]
Oh my bad, I updated the code based on your code. Thank you!
I am glad you solved your problem, if you encounter  with any problem in the code, pls don't forget to mention.
Good days :)
